### ISSUE TITLE
TypeError: null is not an object (evaluating '_reactNative.NativeModules.ReactNativeRootViewBackground.setBackground')

### ISSUE THREAD

**Issue by axelrindle** [pnthach95/react-native-root-view-background#1]
### Problem description

The following call results in the error specified below:

```
useEffect(() => {
    setRootViewBackgroundColor(theme.colors.background)
}, [])
```

Note: `theme.colors.background` is a hex-code like `#121212`

```
TypeError: null is not an object (evaluating '_reactNative.NativeModules.ReactNativeRootViewBackground.setBackground')

This error is located at:
    in App (at App.tsx:78)
    in PersistGate (at App.tsx:77)
    in Provider (at App.tsx:76)
    in Foundation (created by ExpoRoot)
    in ExpoRoot (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/ReactFiberErrorDialog.js:43:2 in showErrorDialog
at hooks/useCachedResources.ts:24:34 in loadResourcesAndDataAsync

[Unhandled promise rejection: TypeError: null is not an object (evaluating '_reactNative.NativeModules.ReactNativeRootViewBackground.setBackground')]
at node_modules/@pnthach95/react-native-root-view-background/src/index.ts:14:4 in setRootViewBackgroundColor
at App.tsx:54:8 in useEffect$argument_0
at hooks/useCachedResources.ts:24:34 in loadResourcesAndDataAsync
```

### Version information
| Module | Version |
| --- | --- |
| Expo | 42.0.1 |
| React Native | [42.0.0 from Expo](https://github.com/expo/react-native/archive/sdk-42.0.0.tar.gz) |

**Comment by pnthach95** [comment]
This dependency does not support managed workflow, you have to eject to bare workflow to use it.
